version: '3.8'

services:
  python_editor:
    container_name: python_editor
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./input:/app/input
      - ./processed:/app/processed
    environment:
      - FLASK_APP=__init__.py
      - FLASK_ENV=development
      - PYTHONPATH=/app
      - API_KEY=${API_KEY}
    networks:
      - n8n-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  input:
  processed:

networks:
  n8n-network:
    external: true
