services:
  python_editor:
    container_name: python_editor
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./input:/app/input
      - ./processed:/app/processed
    environment:
      - FLASK_APP=__init__.py
      - FLASK_ENV=development
      - PYTHONPATH=/app
      - API_KEY=${API_KEY}
    networks:
      - my_custom_network
    restart: unless-stopped

volumes:
  n8n_data:

networks:
  app-network:
    driver: bridge
  my_custom_network:
    external: true
